dataset:
  name: name
model:
  name: base_model
  epochs: 2
  batch_size: 32
  optimizer: adam
  scheduler: plateau
  rnn_type: None
  hidden_size: 0
  num_layers: 0
  learning_rate: 1e-5
  weight_decay: 1e-4
  dropout: .5
  only_test: False
  lf: fl          #wbce, bce, fl
  use_clinical_data: True
  alpha_fl: .6
  gamma_fl: 3
  pos_weight: .8
  augmentation_techniques: ['shear',  'gaussian_noise', 'brightness']
  p_augmentation: .8
  p_augmentation_per_technique: .3
logger:
  log_dir: ./log
  experiment_name: train_base_model
  version: 1
checkpoint:
  monitor: val_loss
  save_top_k: 3
  mode: min