dataset:
  name: name
model:
  name: base_model_enhanced
  epochs: 100
  batch_size: 32
  optimizer: adam
  scheduler: plateau
  rnn_type: None
  hidden_size: 0
  num_layers: 0
  learning_rate: 5e-5
  weight_decay: 1e-3
  dropout: .5
  only_test: False
  lf: fl          #wbce, bce, fl
  use_clinical_data: True
  alpha_fl: .923
  gamma_fl: 3
  pos_weight: .8
  augmentation_techniques: ['random_affine', 'shear', 'random_rotate', 'random_flip']
  p_augmentation: .3
  p_augmentation_per_technique: .3
logger:
  log_dir: ./log
  experiment_name: train_base_model
  version: 1
checkpoint:
  monitor: val_loss
  save_top_k: 1
  mode: min