dataset:
  name: name
model:
  name: base_model_enhancedV2
  epochs: 100
  batch_size: 32
  optimizer: adam
  scheduler: plateau
  rnn_type: None
  hidden_size: 0
  num_layers: 0
  lr: 1e-3
  weight_decay: 5e-4
  dropout: .5
  only_test: False
  lf: fl          #wbce, bce, fl
  use_clinical_data: True
  alpha_fl: .5
  gamma_fl: 2
  pos_weight: .9
  augmentation_techniques: ['random_affine', 'shear', 'random_rotate', 'random_flip']
  p_augmentation: 1.
  depth_attention: .3
logger:
  log_dir: ./log
  experiment_name: train_base_model
  version: 1
checkpoint:
  monitor: val_loss
  save_top_k: 1
  mode: min