dataset:
  name: name
model:
  name: base_model
  epochs: 30
  batch_size: 8
  learning_rate: 1e-5
  optimizer: adam
  scheduler: plateau
  only_test: False
logger:
  log_dir: ./log
  experiment_name: train_base_model
  version: 1
checkpoint:
  monitor: val_loss
  save_top_k: 3
  mode: min