dataset:
  name: name
model:
  name: conv_rnn_cd
  epochs: 100
  batch_size: 2
  optimizer: adam
  scheduler: cosine
  #patience: 1
  learning_rate: 1e-4
  weight_decay: 1e-3
  rnn_type: gru  #rnn, lstm, gru, gru2
  hidden_size: 256
  num_layers: 1
  dropout: .1
  only_test: False

  lf: bce          #wbce, bce, fl
  alpha_fl: .7
  gamma_fl: 3
  pos_weight: 6
  augmentation_techniques: ['shear', 'flip', 'gaussian_noise', 'brightness']
  p_augmentation: .8
  p_augmentation_per_technique: .5
logger:
  log_dir: ./log
  experiment_name: train_conv_rnn
  version: 1
checkpoint:
  monitor: val_loss
  save_top_k: 3
  mode: min