dataset:
  name: name
model:
  name: conv_long_rnn_cd
  epochs: 100
  batch_size: 8
  optimizer: adam
  scheduler: constant
  rnn_type: none
  hidden_size: 45
  learning_rate: 1e-4
  weight_decay: 1e-5
  dropout: .3
  only_test: False

  lf: bce          #wbce, bce, fl
  alpha_fl: .7
  gamma_fl: 2
  pos_weight: .8
  augmentation_techniques: ['shear', 'flip', 'gaussian_noise', 'brightness']
  p_augmentation: .8
  p_augmentation_per_technique: .3
logger:
  log_dir: ./log
  experiment_name: conv_long_lstm_1_cd
  version: 1
checkpoint:
  monitor: val_loss
  save_top_k: 3
  mode: min