dataset:
  name: name
model:
  name: conv_rnn
  epochs: 30
  batch_size: 32
  optimizer: adam
  scheduler: plateau
  #patience: 1
  learning_rate: 1e-4
  weight_decay: 1e-6
  rnn_type: rnn  #rnn, lstm, gru, gru2, transformer
  dropout: .3
  only_test: False

  lf: bce          #wbce, bce, fl
  alpha_fl: .915
  gamma_fl: 2
  pos_weight: 6
  dropout: .3
logger:
  log_dir: ./log
  experiment_name: train_conv_rnn
  version: 1
checkpoint:
  monitor: val_loss
  save_top_k: 3
  mode: min