dataset:
  name: name
model:
  name: conv_lstm
  epochs: 100
  batch_size: 32
  optimizer: sgd
  scheduler: plateau
  rnn_type: lstm
  hidden_size: 48
  num_layers: 2
  lr: 1e-4
  weight_decay: 1e-4
  dropout: .1
  only_test: False
  use_clinical_data: True
  lf: fl          #wbce, bce, fl
  alpha_fl: .2
  gamma_fl: 2
  pos_weight: .8
  augmentation_techniques: ['random_affine', 'shear', 'random_rotate', 'random_flip']
  p_augmentation: .9
  depth_attention: 4
logger:
  log_dir: ./log
  experiment_name: conv_lstm_1_cd_gridsearch
  version: 0
checkpoint:
  monitor: val_loss
  save_top_k: 1
  mode: min