dataset:
  name: name
model:
  name: conv_rnn
  epochs: 150
  batch_size: 2
  optimizer: adam
  scheduler: plateau
  learning_rate: 1e-4
  weight_decay: 1e-3
  rnn_type: rnn  #rnn, lstm, gru, gru2
  hidden_size: 64
  num_layers: 1
  dropout: .3
  only_test: False
  use_clinical_data: True
  lf: fl          #wbce, bce, fl
  alpha_fl: .92
  gamma_fl: 2
  pos_weight: 6
  augmentation_techniques: ['random_affine']
  p_augmentation: .3
  p_augmentation_per_technique: .5
logger:
  log_dir: ./log
  experiment_name: train_conv_rnn
  version: 1
checkpoint:
  monitor: val_loss
  save_top_k: 1
  mode: min