dataset:
  name: name
model:
  name: conv_long_lstm
  epochs: 2
  batch_size: 2
  optimizer: adam
  scheduler: plateau
  rnn_type: none
  hidden_size: 32
  num_layers: 1
  learning_rate: 5e-5
  weight_decay: 1e-4
  dropout: .3
  only_test: False

  use_clinical_data: True
  
  lf: bce          #wbce, bce, fl
  #focal loss hyperparameters
  alpha_fl: .7
  gamma_fl: 2
  #wbce hyperparameters
  pos_weight: .8
  #augmentation hyperparameters
  augmentation_techniques: ['shear',  'gaussian_noise', 'brightness']
  p_augmentation: .8
  p_augmentation_per_technique: .4
logger:
  log_dir: ./log
  experiment_name: conv_long_lstm_1_cd_gridsearch
  version: 0
checkpoint:
  monitor: val_loss
  save_top_k: 3
  mode: min