dataset:
  name: name
model:
  name: conv_long_rnn
  epochs: 50
  batch_size: 16
  optimizer: adam
  scheduler: plateau
  rnn_type: none
  hidden_size: 128
  learning_rate: 1e-5
  weight_decay: 1e-5
  dropout: .5
  only_test: False

  lf: bce          #wbce, bce, fl
  alpha_fl: .7
  gamma_fl: 2
  pos_weight: .8
  augmentation_techniques: ['shear', 'flip', 'gaussian_noise', 'brightness']
  p_augmentation: .8
  p_augmentation_per_technique: .3
logger:
  log_dir: ./log
  experiment_name: train_base_model
  version: 1
checkpoint:
  monitor: val_loss
  save_top_k: 3
  mode: min