dataset:
  name: name
model:
  name: mlp_cd
  epochs: 50
  batch_size: 32
  optimizer: adam
  scheduler: plateau
  rnn_type: None
  hidden_size: 0
  num_layers: 1
  learning_rate: 1e-7
  weight_decay: 1e-3
  dropout: .2
  only_test: False

  lf: bce          #wbce, bce, fl
  alpha_fl: .7
  gamma_fl: 2
  pos_weight: .8
  augmentation_techniques: ['shear', 'flip', 'gaussian_noise', 'brightness']
  p_augmentation: .8
  p_augmentation_per_technique: .3

logger:
  log_dir: ./log
  experiment_name: train_mlp_cd
  version: 1
checkpoint:
  monitor: val_loss
  save_top_k: 3
  mode: min