dataset:
  name: name
model:
  name: mlp_cd
  epochs: 150
  batch_size: 32
  optimizer: adam
  scheduler: plateau
  rnn_type: None
  hidden_size: 0
  num_layers: 1
  lr: 1e-2
  weight_decay: 1e-2
  dropout: 0.3
  only_test: False
  use_clinical_data: True
  lf: fl          #wbce, bce, fl
  alpha_fl: .2
  gamma_fl: 2
  pos_weight: .8
  augmentation_techniques: ['shear',  'gaussian_noise', 'brightness']
  p_augmentation: .0
  p_augmentation_per_technique: .3
logger:
  log_dir: ./log
  experiment_name: train_mlp_cd
  version: 1
checkpoint:
  monitor: val_loss
  save_top_k: 1
  mode: min